[project]
name = "patricio-rey-y-sus-vectorcitos-de-ricota"
version = "0.1.0"
description = ""
authors = [{ name = "Federico Tedin", email = "federicotedin@gmail.com" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4",
    "requests",
    "PyYAML",
    "gensim",
]

[dependency-groups]
dev = ["ruff"]

[tool.uv]
package = false
